### ISSUE TITLE
How Is Data Loaded?

### ISSUE THREAD

**Issue by impulsecorp** [alibaba/lightweight-neural-architecture-search#1]
I read your paper and understand how the entropy score is calculated without using any data, but does the EA part of the program use real data?  I am trying to figure out how to use your program on my own dataset. I see at https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/scripts/classification/README.md you describe how to use the searched model in my own pipeline, but do I use my own data at all to train your program?

**Comment by xiuyu-sxy** [comment]
> I read your paper and understand how the entropy score is calculated without using any data, but does the EA part of the program use real data? I am trying to figure out how to use your program on my own dataset. I see at https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/scripts/classification/README.md you describe how to use the searched model in my own pipeline, but do I use my own data at all to train your program?

hi @impulsecorp 
the EA part  does not need real data. The search process only depends on the entropy score.  And the output is a structure without training. After searching, you can train the model with your own data.
