### ISSUE TITLE
(deepmad) Non-Decreasing Number of Channels part

### ISSUE THREAD

**Issue by ct-wei** [alibaba/lightweight-neural-architecture-search#10]
May I ask if there is code related to the paper (deepmad) Guideline 3. Non-Decreasing Number of Channels part.  I can't find your constraint in (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/tinynas/spaces/mutator/super_res_k1kxk1_mutator.py)

**Comment by kennyorn1** [comment]
Does this mean that if I design MLP the way DeepMAD does, the network width of the MLP will increase as the depth increases?

![mmexport1682385201071](https://user-images.githubusercontent.com/110704880/234151895-8abcf37b-d0bf-467f-bf93-4b8a53ca7df7.jpg)

As shown in Guideline 3 and thr yellow underline.

**Comment by kennyorn1** [comment]
Does this mean that if I design MLP the way DeepMAD does, the network width of the MLP will increase as the depth increases?

![mmexport1682385201071](https://user-images.githubusercontent.com/110704880/234151895-8abcf37b-d0bf-467f-bf93-4b8a53ca7df7.jpg)

As shown in Guideline 3 and thr yellow underline.

**Comment by kennyorn1** [comment]
> May I ask if there is code related to the paper (deepmad) Guideline 3. Non-Decreasing Number of Channels part. I can't find your constraint in (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/tinynas/spaces/mutator/super_res_k1kxk1_mutator.py)

Does this mean that if I design MLP the way DeepMAD does, the network width of the MLP will increase as the depth increases?

![mmexport1682385201071](https://user-images.githubusercontent.com/110704880/234152158-cbac67e9-0457-46a9-975e-cd30d765c624.jpg)

As shown in Guideline 3 and the yellow underline.

**Comment by slacklife** [comment]
> May I ask if there is code related to the paper (deepmad) Guideline 3. Non-Decreasing Number of Channels part. I can't find your constraint in (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/tinynas/spaces/mutator/super_res_k1kxk1_mutator.py)

Thank you for your attention to DeepMAD!
This is a bug left over during the ablation phase and it has been [fixed](https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/tinynas/spaces/mutator/super_res_k1kxk1_mutator.py#L58)(Line58-60).
