### ISSUE TITLE
Whether the formula to calculate the entropy of mlp is universal?

### ISSUE THREAD

**Issue by kennyorn1** [alibaba/lightweight-neural-architecture-search#11]
![image](https://user-images.githubusercontent.com/110704880/234178830-9ab8b424-1174-40e5-9fb4-08433d65b681.png)

I went over how you derived the entropy of the MLP. I found that the final formula needed to be based on the standard normal distribution assumption in box 1, which also resulted in the entropy of the MLP being dependent only on the model structure of the MLP itself (the width of each layer and the depth of the network), not on the weight and input of the network.

So when I use this formula based on the standard normal distribution hypothesis to design the MLP network, can I really not care about the weight of the network and the input distribution？

**Comment by slacklife** [comment]
Thank you for your attention to DeepMAD!

According to the authors' knowledge, this formula is transferable to MLP.
However,  some guidelines need to be adapted to achieve a good result.
We are not sure whether the guidelines in this paper are adapted to the MLP network.

Also, I'm curious about your demand scenarios using pure MLP networks.

**Comment by kennyorn1** [comment]
> 

Thanks for replying!

My application scenario is relatively simple, which is a prediction task in the field of materials.

Basically, I have two thousand training samples, and each sample consists of an input feature, which is a one-dimensional vector of length 20 (meaning that the input layer of the MLP can be 20 neurons), and an output feature, which is a scalar (e.g., the lifetime of this material).

I wanted to search for the MLP structure best suited to my task, based on the theoretical formula proposed by DeepMAD.

**Comment by slacklife** [comment]
It is cool to use DeepMAD !
Please let us know when you have good results with DeepMAD !

**Comment by kennyorn1** [comment]
> It is cool to use DeepMAD ! Please let us know when you have good results with DeepMAD !

Hahaha😂

Do you have implemented the code to search for the appropriate MLP structure with DeepNAS？ If not, I will program it myself.

If good progress is made, I will share it with you hahaha

**Comment by slacklife** [comment]
Not yet.
DeepMAD is proposed on CNN networks.
We welcome collaborators to extend this to MLP.

**Comment by kennyorn1** [comment]
> Not yet. DeepMAD is proposed on CNN networks. We welcome collaborators to extend this to MLP.



> Not yet. DeepMAD is proposed on CNN networks. We welcome collaborators to extend this to MLP.

That will be interesting.

By the way, have you studied how the addition of the attention mechanism changes the entropy of the network?

**Comment by kennyorn1** [comment]
> Not yet. DeepMAD is proposed on CNN networks. We welcome collaborators to extend this to MLP.

![image](https://user-images.githubusercontent.com/110704880/234454704-32e0465d-2b31-4b5c-a3c5-f94190413b8f.png)

I think this should be 'L-1' if I don't misunderstand.

**Comment by slacklife** [comment]
No,  Please take a look at `i` starting from 1.

**Comment by kennyorn1** [comment]
![image](https://user-images.githubusercontent.com/110704880/234461306-014a4e29-18ba-417d-9c7f-f0f362f7ad26.png)

I'm still confused.

**Comment by kennyorn1** [comment]
![image](https://user-images.githubusercontent.com/110704880/234461833-2b6f0029-8f57-429b-a471-d0692aac454d.png)

If I use 'L', answer will be this.
