### ISSUE TITLE
How to search in custom search space such as HardNet?

### ISSUE THREAD

**Issue by 1chimaruGin** [alibaba/lightweight-neural-architecture-search#2]
Could you please provide step by step procedure?

**Comment by Vericoware** [comment]
1. Build a "superxxxxx.py" like "SuperResConvK1KXK1.py" (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/nas/models/blocks/SuperResConvK1KXK1.py)
2. Implement "entropy_forward" or "get_log_zen_score" functions in your "superxxxxx.py"
3. Write your own "masterhardnet.py" like "masternet.py" (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/nas/models/masternet.py).
4. Specialize your own "configxxx.py" for searching like "config_nas.py" (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/configs/config_nas.py).
5. Design your own search space file "space_xxxx.py" like "space_K1KXK1.py" (https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/nas/spaces/space_K1KXK1.py).
6. Finally, run and debug.

**Comment by 1chimaruGin** [comment]
Got it.

Thank you!@Vericoware
