### ISSUE TITLE
Is the reported mAP iou=0.5 or iou=0.5:0.95

### ISSUE THREAD

**Issue by jsrimr** [alibaba/lightweight-neural-architecture-search#3]
I want to compare the MAE-DET model with YoloV5, 
but cannot find whether the MAE-DET use threshold 0.5 or 0.5:0.95 to compute mAP.

**Comment by Vericoware** [comment]
We used threshold 0.5:0.95 to compute mAP, which follows the implementation of GFV2 (https://github.com/implus/GFocalV2).
