### ISSUE TITLE
The calculation of FLOPs seems to be wrong

### ISSUE THREAD

**Issue by jianhuiliao** [alibaba/lightweight-neural-architecture-search#7]
The FLOPs calculation during the search is missing the multiplication by 2.

```python
def get_flops(self, resolution):
        # return self.flops * resolution**2
        return self.flops * resolution ** 2 * 2
```

**Comment by slacklife** [comment]
Hello !
In this repo and DeepMAD paper,  the `FLOPs` refers the numbers of multiplier–accumulator (MAC unit), which is similar to `MACs` in some paper.

All backbones were compared under the same setting in experiments.
